name: artifact-workflow

on: 
  push:
    branches: 
      - main

  workflow_dispatch: 

jobs:
  create_artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - shell: bash
        run: |
          echo Sample > sample.txt
          
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sample-text
          path: sample.txt

  use_artifact:
    needs: create_artifact
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts
        uses:  actions/download-artifact@v4
        with:
          name: sample-text

      - shell: bash
        run: |
          value=`cat sample.txt`
          echo $value
